"""empty message

Revision ID: 92708379942d
Revises: 2a679659c72f
Create Date: 2018-05-25 14:51:16.648266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92708379942d'
down_revision = '2a679659c72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('account_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'account_amount')
    # ### end Alembic commands ###
